language: python
    python:
      - "3.8"
    services:
      - postgresql
    env:
      -DB=postgresql
    install:
      - pip install -r requirements.txt
    before_script:
      - psql -c 'create database test;' -U postgres
    script:
      - python manage.py test
