version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:3001
    restart: always
    volumes:
      - .:/code
    ports:
      - "3001:3001"
    depends_on:
      - db
